# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mozilla-SourceViewer
version:      0.04
version_from: lib/Mozilla/SourceViewer.pm
installdirs:  site
requires:
    File::Slurp:                   
    Mozilla::Mechanize:            0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
